### ISSUE TITLE
British Library UX issues for testing

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#341]
An overview of on-going issues for consideration in testing
- [x] Navigation tweaks - thumbnail/single/double page view; sequence controls https://github.com/UniversalViewer/universalviewer/issues/339
- [x] White teardrop as location indicator https://github.com/UniversalViewer/universalviewer/issues/337
- [ ] Responsive UI (was 'Cover page') https://github.com/UniversalViewer/universalviewer/issues/334
- [ ] Two-up / one-up mode UX issues https://github.com/UniversalViewer/universalviewer/issues/338
- [ ] Print https://github.com/UniversalViewer/universalviewer/issues/331
- [ ] Separating share and embed options into separate icons and dialogue boxes https://github.com/UniversalViewer/universalviewer/issues/330
- [ ] Download experience
  e.g. labels for different download sizes (https://github.com/UniversalViewer/universalviewer/issues/142#issuecomment-230299938); downloading image/canvas vs item
- [ ] Share/embed header style to 18px like Download, Config header style
- [x] @edsilv 'more info' text currently goes to https://github.com/universalviewer/universalviewer which has useful information when the reader scrolls down but the initial screen is geektastic. Using the anchored link https://github.com/universalviewer/universalviewer#contributors is a slightly better experience 

**Points to test**
- Printing
- Share. How do people expect 'share' to work? Does it adequately cover bookmarking? Are you sharing/bookmarking the page, chapter, book, or the viewport? Does it behave as a user would expect?
- Embed
- Navigation - moving between pages; understanding where you are in the item (previous issue with page vs image number); understanding what you're looking at. 
- Which navigation controls do people use?
- Single vs double page view issues - do people understand the new icons on the top right-hand corner?
- Search within. Does it disappear if there's no text to search? Is the highlight colour visible enough? Do people understand the teardrops as navigation? Does the stemming cause issues? Would people like to use exact search phrases?
- Understanding what you can do with the item - can I print it, download it, save it in other ways?
- Mobile functionality and responsive design
- Feedback
- Usage terms / attribution statement - are rights issues handled gracefully?
- 'More information' panel. Affordances (do people realise it's there? Would changing the icon to an 'i' help, or some other alternative to the chevron?) Content - do the field labels make sense, are any fields missing?
- Previous tests indicate that people don't understand the 'Navigator Enabled' text on the Config screen - is there a better label for it?

Search terms for catalogue to viewer (end-to-end) searches: blww1, blmsd

Other: 3D navigation isn't always intuitive, and some instructions or hints appropriate to the object should be available to viewers e.g. how to manipulate objects in space, not just zoom in and out.

**Comment by adunning** [comment]
It didn't come up because we were only testing on PCs, but #325 is also a result of this testing.

**Comment by mialondon** [comment]
First pass at a test with internal reference staff:

First impressions (load, think aloud)
Assume the first minutes include some unguided exploration as they do first impressions?
Navigation within an item (e.g. navigate to page 10)
Search within an item
Download
Print
Share
Embed?

**Comment by mialondon** [comment]
In three tests today, no-one used the double arrow/chevrons to open up the thumbnail panel across the width of the page. Together with the lack of structural metadata to use in the 'contents' tab, this supports the suggestion to remove the left-hand panel and move the thumbnail option to a tidied thumb/double/single page view area.

However, some people find the thumbnail navigation quite intuitive - would it work as well if they had to flip between thumbnail view and page view?

Thoughts, @edsilv @jennpb ?

**Comment by mialondon** [comment]
This is probably just a config file change, but usability testing result: change 'Download Selection' text to 'Select pages to download' (tfs Bug 13411).

**Comment by edsilv** [comment]
@mialondon I think indications are that the left-hand-side thumbs are ok as they are, but the expanded gallery view is hardly ever used. I agree that we should add a new "grid" icon as per: https://github.com/UniversalViewer/universalviewer/issues/339 instead of using the chevrons. If we're moving the "download selection" option to a separate dialogue, I'd first need to make a gallery component. This could then be used in both expanded view and the dialogue.

**Comment by mialondon** [comment]
@edsilv yes. People instinctively used the thumbnail grid and explicitly said how much they liked it, so the usability tests definitely reaffirmed its value. The chevrons, OTOH, are overlooked - people just don't see them as navigational, which adds support for the plan to have thumb/double/single page view icons and a gallery component.

**Comment by mialondon** [comment]
re https://github.com/UniversalViewer/universalviewer/issues/331 - the implementation of this will need review before future BL work as the user experience for print and download is currently affected by implementation decisions. (e.g. you should be able to download or print from an embedded item).

**Comment by mialondon** [comment]
@edsilv Is the page/image number function working at the moment? (Hide page number if only image numbers?) Are thumbnails labelled with an image number rather than a page number? It's not clear it's a toggle between image and page number - also could it update to e.g. the page number when you change between them?

**Comment by mialondon** [comment]
@edsilv the solution for the image/page dropdown on https://github.com/UniversalViewer/universalviewer/issues/339 matches solutions Donald and I had discussed for the toggle between images and pages being unclear.

One further thing - if the manifest has no page metadata (assuming that's where it comes from), can the viewer suppress the page option (i.e. not make it a drop-down)?

**Comment by mialondon** [comment]
Points for future consideration - the current BL itemviewer does a good job of indicating your place in the sequence (and providing an image number) while also allowing the user to jump to the start/end or drag the viewer to a specific place in the sequence. Something to consider for the 'current place' indicator and in-item navigation?

**Comment by mialondon** [comment]
https://github.com/UniversalViewer/universalviewer/issues/357#issuecomment-239808826

**Comment by mialondon** [comment]
Notes in progress at https://docs.google.com/document/d/1XON9y57vbSrHVRKAMzC14GNCqbYK0p_PmSxiNH9OkmI/edit?usp=sharing - probably has lots of shorthand and project jargon so excuse the mess!
